feat: Course Dates
openedx/openedx-app-ios pull request #137
Opened 2023-10-26 12:08 UTC by mumer92

2023-10-31 12:34 UTC, volodymyr-chekyrta requested changes

2023-10-31 12:34 UTC, volodymyr-chekyrta commented on Course/Course/Domain/Model/CourseDates.swift
> +                title: "Today",
It would be great to move this to string resources for translations.

2023-10-31 12:34 UTC, volodymyr-chekyrta commented on Course/Course/Domain/Model/CourseDates.swift
> +            return "Verified Only"
Same to these.
It would be great to move them to string resources for translations.

2023-10-31 12:34 UTC, volodymyr-chekyrta commented on Core/Core.xcodeproj.xcworkspace/xcuserdata/m.umer.xcuserdatad/UserInterfaceState.xcuserstate
Seems like .gitignore issue, xcuserdata/m.umer.xcuserdatad folder should be ignored

2023-10-31 12:34 UTC, volodymyr-chekyrta commented on Course/Course/Presentation/Dates/CourseDatesView.swift
> +            return ("Unreleased", Color.white.opacity(0), Color.white.opacity(0))
Let's also move these strings to the Localizable.strings for translations

2023-10-31 12:34 UTC, volodymyr-chekyrta commented on Course/Course/Presentation/Dates/CourseDatesViewModel.swift
> +    }
Unnecessary public level modifier if we use it only in the Course module

2023-10-31 12:34 UTC, volodymyr-chekyrta commented on Core/Core.xcodeproj/project.xcworkspace/xcuserdata/m.umer.xcuserdatad/UserInterfaceState.xcuserstate
Seems like .gitignore issue, xcuserdata/m.umer.xcuserdatad folder should be ignored

2023-10-31 12:34 UTC, volodymyr-chekyrta commented on Course/Course.xcodeproj/project.xcworkspace/xcuserdata/m.umer.xcuserdatad/UserInterfaceState.xcuserstate
Seems like .gitignore issue, xcuserdata/m.umer.xcuserdatad folder should be ignored

2023-10-31 12:34 UTC, volodymyr-chekyrta commented on Discovery/Discovery.xcodeproj/project.xcworkspace/xcuserdata/m.umer.xcuserdatad/UserInterfaceState.xcuserstate
Seems like .gitignore issue, xcuserdata/m.umer.xcuserdatad folder should be ignored

2023-11-01 07:15 UTC, mumer92 commented
@volodymyr-chekyrta i have updated the PR, added translations and added few files to .gitignore to ignore the files that were previously checked into the repo.

2023-11-01 08:23 UTC, volodymyr-chekyrta commented
@mumer92 Thank you! 🙌

Would you mind to check the `CourseDateBlock` file? 
I noticed that `var blockTitle: String` appears to still be hardcoded. 

Could you also check those files? I'm uncertain, but it seems to me that they may still be present in the project:
`
Core/Core.xcodeproj.xcworkspace/xcuserdata/m.umer.xcuserdatad
Course/Course.xcodeproj/project.xcworkspace/xcuserdata/m.umer.xcuserdatad
Discovery/Discovery.xcodeproj/project.xcworkspace/xcuserdata/m.umer.xcuserdatad
`

2023-11-01 08:37 UTC, volodymyr-chekyrta approved these changes

2023-11-01 09:25 UTC, volodymyr-chekyrta approved these changes

2023-11-01 12:34 UTC, eyatsenkoperpetio approved these changes

2023-11-02 07:54 UTC, merged

2023-11-03 14:52 UTC, eyatsenkoperpetio commented
Hi, small problem @mumer92 
<img width="408" alt="Screenshot 2023-11-03 at 15 48 59" src="https://github.com/openedx/openedx-app-ios/assets/76485998/a4a9cb49-4c41-4ad5-ae6a-68ceff4c47ba">

2023-11-06 11:38 UTC, mumer92 commented
@eyatsenkoperpetio i have created https://github.com/openedx/openedx-app-ios/pull/149

2023-11-07 19:10 UTC, touchapp commented
@marcotuts can we have Sam take a look at this? I think it needs some design love.