Theming whitelabel.py script
openedx/openedx-app-ios pull request #214
Opened 2023-12-19 14:47 UTC by rnr

# Added the theming `whitelabel.py` script

This script can override Assets (images, colors, app Icon) and change project settings (app bundle ID and development team ID). Please follow [this documentation](https://github.com/touchapp/openedx-app-ios/blob/config-whitelabel-script/Documentation/Theming_implementation.md) to install Python dependencies if needed and to read how to work/configure.

## Changes

### 1) Allocated colors for more flexibility:

- `loginNavigationText`
- `loginBackground`
- `accentButtonColor`
- `SplashBackground`

### 2) Added `ThemeConfig` for feature flags related to Theming

### 3) Changed `textInputShape` and `buttonShape` to support rounded and rectangle corners.

## Custom edX theme example

1. Clone `https://github.com/edx/edx-mobile-config` into the OpenEdX root folder and switch to the `anton/openedX-theming` branch.

2. From the OpenEdX root folder, run the script as:
```bash
python config_script/whitelabel.py --config-file=edx-mobile-config/openEdXAssets/whitelabel.yaml -v
```
3. Install on your simulator or device

All possible config parameters are described in [this documentation](https://github.com/touchapp/openedx-app-ios/blob/config-whitelabel-script/Documentation/Theming_implementation.md)

2023-12-22 06:03 UTC, miankhalid commented
@shafqat-muneer will be reviewing this PR from Axinite's side.

2023-12-22 14:13 UTC, shafqat-muneer commented
PR review is in progress from my side.

2023-12-26 16:43 UTC, shafqat-muneer commented
After running this command on terminal:
```
python3 config_script/whitelabel.py --config-file=path/to/configfile/whitelabel.yaml -v
```

Got this error:
```
File "/path/to/config_script/whitelabel.py", line 6, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

Resolved the issue by installing `pyyaml` by following command:
```
pip3 install pyyaml
```

**Suggestion:** I think we should document every dependency in `Theming_implementation.md` file so that it can easily be configured on new system independently.

2023-12-26 17:21 UTC, shafqat-muneer commented
We utilize distinct bundle identifiers for our Development (Dev), Staging (Stage), and Production (Prod) environments. Is it possible to modify the bundle identifiers for all environments simultaneously, or do we need to execute the script multiple times to update each environment's bundle identifier individually?

2023-12-26 17:21 UTC, shafqat-muneer requested changes

2023-12-26 17:32 UTC, shafqat-muneer commented
Review is in progress.

2023-12-27 06:58 UTC, shafqat-muneer commented
@rnr Getting `SyntaxWarning` after running command:
```
python3 config_script/whitelabel.py --config-file=/path/to/whitelabel.yaml
```

Error Details:
```
/path/to/config_script/whitelabel.py:317: SyntaxWarning: invalid escape sequence '\*'
  return f"/\* {build_config} \*/ = {{\n\t\t\tisa = XCBuildConfiguration;\n\t\t\tbaseConfigurationReference = [\s|\S]*\t\t\tname = {build_config};"
/path/to/config_script/whitelabel.py:317: SyntaxWarning: invalid escape sequence '\*'
  return f"/\* {build_config} \*/ = {{\n\t\t\tisa = XCBuildConfiguration;\n\t\t\tbaseConfigurationReference = [\s|\S]*\t\t\tname = {build_config};"
/path/to/config_script/whitelabel.py:317: SyntaxWarning: invalid escape sequence '\s'
  return f"/\* {build_config} \*/ = {{\n\t\t\tisa = XCBuildConfiguration;\n\t\t\tbaseConfigurationReference = [\s|\S]*\t\t\tname = {build_config};"
```

2023-12-27 09:40 UTC, rnr commented
> @rnr Getting `SyntaxWarning` after running command:
> 
> ```
> python3 config_script/whitelabel.py --config-file=/path/to/whitelabel.yaml
> ```
> 
> Error Details:
> 
> ```
> /path/to/config_script/whitelabel.py:317: SyntaxWarning: invalid escape sequence '\*'
>   return f"/\* {build_config} \*/ = {{\n\t\t\tisa = XCBuildConfiguration;\n\t\t\tbaseConfigurationReference = [\s|\S]*\t\t\tname = {build_config};"
> /path/to/config_script/whitelabel.py:317: SyntaxWarning: invalid escape sequence '\*'
>   return f"/\* {build_config} \*/ = {{\n\t\t\tisa = XCBuildConfiguration;\n\t\t\tbaseConfigurationReference = [\s|\S]*\t\t\tname = {build_config};"
> /path/to/config_script/whitelabel.py:317: SyntaxWarning: invalid escape sequence '\s'
>   return f"/\* {build_config} \*/ = {{\n\t\t\tisa = XCBuildConfiguration;\n\t\t\tbaseConfigurationReference = [\s|\S]*\t\t\tname = {build_config};"
> ```

@shafqat-muneer  Could you show what is content of whitelabel.yaml file for this error please

2023-12-27 10:44 UTC, shafqat-muneer commented
> > @rnr Getting `SyntaxWarning` after running command:
> > ```
> > python3 config_script/whitelabel.py --config-file=/path/to/whitelabel.yaml
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Error Details:
> > ```
> > /path/to/config_script/whitelabel.py:317: SyntaxWarning: invalid escape sequence '\*'
> >   return f"/\* {build_config} \*/ = {{\n\t\t\tisa = XCBuildConfiguration;\n\t\t\tbaseConfigurationReference = [\s|\S]*\t\t\tname = {build_config};"
> > /path/to/config_script/whitelabel.py:317: SyntaxWarning: invalid escape sequence '\*'
> >   return f"/\* {build_config} \*/ = {{\n\t\t\tisa = XCBuildConfiguration;\n\t\t\tbaseConfigurationReference = [\s|\S]*\t\t\tname = {build_config};"
> > /path/to/config_script/whitelabel.py:317: SyntaxWarning: invalid escape sequence '\s'
> >   return f"/\* {build_config} \*/ = {{\n\t\t\tisa = XCBuildConfiguration;\n\t\t\tbaseConfigurationReference = [\s|\S]*\t\t\tname = {build_config};"
> > ```
> 
> @shafqat-muneer Could you show what is content of whitelabel.yaml file for this error please

@rnr I tried it with just `import_dir` content. `whitelabel.yaml` looks like this:
```
import_dir: '/Users/shafqatmuneer/msmq/Projects/2U/_Daily/20231226/Images' # folder where importing images are placed
```

I also checked with same sample file content in config repo, it's also giving error. With `whitelabel.yaml` file in config repo, error is this:
```
/Users/shafqatmuneer/msmq/Projects/2U/CodeBase/openedx-app-ios/config_script/whitelabel.py:317: SyntaxWarning: invalid escape sequence '\*'
  return f"/\* {build_config} \*/ = {{\n\t\t\tisa = XCBuildConfiguration;\n\t\t\tbaseConfigurationReference = [\s|\S]*\t\t\tname = {build_config};"
/Users/shafqatmuneer/msmq/Projects/2U/CodeBase/openedx-app-ios/config_script/whitelabel.py:317: SyntaxWarning: invalid escape sequence '\*'
  return f"/\* {build_config} \*/ = {{\n\t\t\tisa = XCBuildConfiguration;\n\t\t\tbaseConfigurationReference = [\s|\S]*\t\t\tname = {build_config};"
/Users/shafqatmuneer/msmq/Projects/2U/CodeBase/openedx-app-ios/config_script/whitelabel.py:317: SyntaxWarning: invalid escape sequence '\s'
  return f"/\* {build_config} \*/ = {{\n\t\t\tisa = XCBuildConfiguration;\n\t\t\tbaseConfigurationReference = [\s|\S]*\t\t\tname = {build_config};"
```

2023-12-27 14:00 UTC, rnr commented on Documentation/Theming_implementation.md
> +- `pip install pillow`
added to documentation all dependencies which are not default python's libs

2023-12-27 14:00 UTC, rnr commented on Documentation/Theming_implementation.md
> +The theming script `whitelabel.py` can be ran from the OpenEdX iOS root project folder with the following command:
fixed

2023-12-27 14:04 UTC, rnr commented on config_script/whitelabel.py
> +        # Config file can contain next optins:
fixed

2023-12-27 14:06 UTC, rnr commented
> > > @rnr Getting `SyntaxWarning` after running command:
> > > ```
> > > python3 config_script/whitelabel.py --config-file=/path/to/whitelabel.yaml
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Error Details:
> > > ```
> > > /path/to/config_script/whitelabel.py:317: SyntaxWarning: invalid escape sequence '\*'
> > >   return f"/\* {build_config} \*/ = {{\n\t\t\tisa = XCBuildConfiguration;\n\t\t\tbaseConfigurationReference = [\s|\S]*\t\t\tname = {build_config};"
> > > /path/to/config_script/whitelabel.py:317: SyntaxWarning: invalid escape sequence '\*'
> > >   return f"/\* {build_config} \*/ = {{\n\t\t\tisa = XCBuildConfiguration;\n\t\t\tbaseConfigurationReference = [\s|\S]*\t\t\tname = {build_config};"
> > > /path/to/config_script/whitelabel.py:317: SyntaxWarning: invalid escape sequence '\s'
> > >   return f"/\* {build_config} \*/ = {{\n\t\t\tisa = XCBuildConfiguration;\n\t\t\tbaseConfigurationReference = [\s|\S]*\t\t\tname = {build_config};"
> > > ```
> > 
> > 
> > @shafqat-muneer Could you show what is content of whitelabel.yaml file for this error please
> 
> @rnr I tried it with just `import_dir` content. `whitelabel.yaml` looks like this:
> 
> ```
> import_dir: '/Users/shafqatmuneer/msmq/Projects/2U/_Daily/20231226/Images' # folder where importing images are placed
> ```
> 
> I also checked with same sample file content in config repo, it's also giving error. With `whitelabel.yaml` file in config repo, error is this:
> 
> ```
> /Users/shafqatmuneer/msmq/Projects/2U/CodeBase/openedx-app-ios/config_script/whitelabel.py:317: SyntaxWarning: invalid escape sequence '\*'
>   return f"/\* {build_config} \*/ = {{\n\t\t\tisa = XCBuildConfiguration;\n\t\t\tbaseConfigurationReference = [\s|\S]*\t\t\tname = {build_config};"
> /Users/shafqatmuneer/msmq/Projects/2U/CodeBase/openedx-app-ios/config_script/whitelabel.py:317: SyntaxWarning: invalid escape sequence '\*'
>   return f"/\* {build_config} \*/ = {{\n\t\t\tisa = XCBuildConfiguration;\n\t\t\tbaseConfigurationReference = [\s|\S]*\t\t\tname = {build_config};"
> /Users/shafqatmuneer/msmq/Projects/2U/CodeBase/openedx-app-ios/config_script/whitelabel.py:317: SyntaxWarning: invalid escape sequence '\s'
>   return f"/\* {build_config} \*/ = {{\n\t\t\tisa = XCBuildConfiguration;\n\t\t\tbaseConfigurationReference = [\s|\S]*\t\t\tname = {build_config};"
> ```

@shafqat-muneer added extra escaping to regex inside python script. should be fine now. please check

2023-12-27 16:50 UTC, shafqat-muneer approved these changes
LGTM
- Script is working
- Documentation related improvements are done
- Dependencies are listed
- Sample `whitelabel.yaml` file added

<img width="1360" alt="Screenshot 2023-12-27 at 9 08 04 PM" src="https://github.com/openedx/openedx-app-ios/assets/11990137/7c89bf52-da0e-48c2-9a08-6a477655d18b">

2024-01-02 08:49 UTC, volodymyr-chekyrta commented
Hello everyone!

I was wondering if we are waiting for @eyatsenkoperpetio review before merging this PR, or if we can go ahead and merge it now?

2024-01-02 15:54 UTC, eyatsenkoperpetio approved these changes

2024-01-02 15:57 UTC, rnr commented
> Hello everyone!
> 
> I was wondering if we are waiting for @eyatsenkoperpetio review before merging this PR, or if we can go ahead and merge it now?

Hello @volodymyr-chekyrta 
I think we are ready to merge since @eyatsenkoperpetio just approved 
Thank you

2024-01-02 17:38 UTC, merged