Unit progress navigation style
openedx/openedx-app-ios pull request #258
Opened 2024-01-25 12:43 UTC by rnr

This PR is for next issues:
- https://github.com/openedx/openedx-app-ios/issues/200
- https://github.com/openedx/openedx-app-ios/issues/206
- https://github.com/openedx/openedx-app-ios/issues/215

Added a progress bar at the top of the content screen. Each block can have one of four states:
- selected completed
- selected incomplete
- completed unselected
- incomplete unselected

If the progress line is present, the navigation style changes from `vertical` to `horizontal`. 
This was done with `COURSE_UNIT_PROGRESS_ENABLED` FF - please use the configuration branch https://github.com/edx/edx-mobile-config/tree/saeed/openedX

https://github.com/openedx/openedx-app-ios/assets/37253/0351364d-50a4-4507-a84f-959b859e954b

2024-01-30 13:38 UTC, saeedbashir requested changes
<img width="342" alt="image" src="https://github.com/openedx/openedx-app-ios/assets/5606473/23a78593-8ad9-499d-bb20-6c73eb7de944">

Shouldn't the arrow icon on the `previous` button in the unit navigation be on the left side of the text?

2024-01-30 13:38 UTC, saeedbashir commented on Core/Core/Configuration/Config/UIComponentsConfig.swift
> +        courseUnitProgressEnabled = dictionary[Keys.courseUnitProgressEnabled.rawValue] as? Bool ?? false
You can inherit the Keys enum from `RawStringExtractable` so that you don't have to mention `.rawValue` while extracting the data from dictionary.

2024-01-30 13:38 UTC, saeedbashir commented on Core/Core/Providers/Ajax/AjaxProvider.swift
> +}
Notifications are centralized in `Core/Notification.swift`. Can you please move this notification to there as well.

2024-01-30 13:38 UTC, saeedbashir commented on Core/Core/View/Base/Webview/WebView.swift
> +    var isAddAjaxCallbackScript: Bool
How about renaming it to `addAjaxCallbackScript` thoughts?

2024-01-30 13:38 UTC, saeedbashir commented on Core/Core/View/Base/Webview/WebView.swift
> +        let ajaxProvider = AjaxProvider()
I'm not sure whether we need to specify access level`fileprivate` here or not because we are not using it for other variables, what do you think?

2024-01-30 13:38 UTC, saeedbashir commented on Course/Course/Presentation/Unit/CourseUnitView.swift
> +
Please move this notification to `Core/Notifications`.

2024-01-30 13:38 UTC, saeedbashir commented on Course/Course/Presentation/Video/VideoPlayerViewModel.swift
> +    public var didUnitCompletion: (() -> Void)?
Unused code can be removed.

2024-01-30 20:22 UTC, rnr commented
> <img alt="image" width="342" src="https://private-user-images.githubusercontent.com/5606473/300825779-23a78593-8ad9-499d-bb20-6c73eb7de944.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NDY0MDksIm5iZiI6MTcwNjY0NjEwOSwicGF0aCI6Ii81NjA2NDczLzMwMDgyNTc3OS0yM2E3ODU5My04YWQ5LTQ5OWQtYmIyMC02YzczZWI3ZGU5NDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzBUMjAyMTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWNkOGJmYzdiNzIyYmM5NmQ3ZmVkMDJhNjYzYWM3YzRjNzk0Yjc3ZGY1OTQyNWY1YWFjZTg5NDQ5ZTZlNDVmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G5AeCFT-R_DG9yWqQCzH_O9LbLgj35hYZOBBT9yve54">
> Shouldn't the arrow icon on the `previous` button in the unit navigation be on the left side of the text?

thank you for the highlighting
fixed

2024-02-01 11:44 UTC, saeedbashir commented
The progress gets lost in the same run if go back and come to the same screen.

https://github.com/openedx/openedx-app-ios/assets/5606473/1caa8d13-8e7a-4afb-8af9-49297efd7c20

2024-02-02 04:48 UTC, saeedbashir commented on Course/Course/Presentation/Unit/CourseUnitView.swift
> +                        }
@eyatsenkoperpetio  In which case this notification gets posted, I've checked this isn't calling when setting the `blockChanged = true`?

2024-02-02 14:10 UTC, volodymyr-chekyrta approved these changes

2024-02-02 14:11 UTC, merged

2024-02-02 14:11 UTC, volodymyr-chekyrta commented
🚀 🚀 🚀