Update youtube player package version to 1.8.0
openedx/openedx-app-ios pull request #395
Opened 2024-04-15 14:33 UTC by rnr

Getting the latest version of the YouTubePlayerKit package causes compilation errors . This PR fixes this problem.

2024-04-15 14:39 UTC, forgotvas requested changes

2024-04-15 14:39 UTC, forgotvas commented on Course/Course/Presentation/Video/YouTubeVideoPlayer.swift
> +                                    viewModel.youtubePlayer.seek(
please use pattern one parameter with value at line

2024-04-15 14:40 UTC, forgotvas approved these changes

2024-04-16 07:53 UTC, volodymyr-chekyrta approved these changes

2024-04-16 12:06 UTC, saeedbashir approved these changes

2024-04-17 10:28 UTC, merged