[iOS] Completion doesn't work for videos in PiP mode.
openedx/openedx-app-ios pull request #414
Opened 2024-04-22 14:09 UTC by forgotvas

Fix bug for:
[iOS] Completion doesn't work for videos in PiP mode. #391

A little refactor how players is build in.

2024-05-07 15:12 UTC, shafqat-muneer commented
@forgotvas I just noticed that even though the video is still playing in PiP mode, when I return from other screens, it appears as if the module has been completed.

https://github.com/openedx/openedx-app-ios/assets/11990137/9d5c517b-8fd5-43b1-9d60-77a33eb3633a

2024-05-07 15:26 UTC, shafqat-muneer commented
> @forgotvas I just noticed that even though the video is still playing in PiP mode, when I return from other screens, it appears as if the module has been completed.
> 
>  PiP.Mode.Video.mov

I came across this code snippet, and it appears to be functioning as intended, so there's no need to make any changes to it. 🎉 
```
if strongSelf.playerTracker.progress > 0.8 && !strongSelf.isViewedOnce {
                    strongSelf.isViewedOnce = true
                    Task {
                        await strongSelf.sendCompletion()
                    }
                }
```

2024-05-08 16:45 UTC, shafqat-muneer commented
@forgotvas I'm curious to understand what happens if a user downloads a video and watches it offline. Does the system recognize it as complete once the user reconnects online?

2024-05-09 10:49 UTC, shafqat-muneer requested changes

2024-05-09 10:49 UTC, shafqat-muneer commented on Course/Course/Presentation/Video/SubtittlesView.swift
Typo: `SubtittlesView` to `SubtitlesView`

2024-05-09 12:33 UTC, forgotvas commented
> @forgotvas I'm curious to understand what happens if a user downloads a video and watches it offline. Does the system recognize it as complete once the user reconnects online?

Hi @shafqat-muneer, you are right, it will try to call the completion request, but as we are offline it will not be send. Also in current implementation i don't see that we are syncing it after return to online mode. But that PR is fixing problem when we call completion for videos what you are playing in PIP mode, to solve offline sync we need to create another task & PR. @sergeymomot could create ticket for that.

 I have fixed code that you requested to change. Thank you for review.

2024-05-09 12:56 UTC, shafqat-muneer commented
> > @forgotvas I'm curious to understand what happens if a user downloads a video and watches it offline. Does the system recognize it as complete once the user reconnects online?
> 
> Hi @shafqat-muneer, you are right, it will try to call the completion request, but as we are offline it will not be send. Also in current implementation i don't see that we are syncing it after return to online mode. But that PR is fixing problem when we call completion for videos what you are playing in PIP mode, to solve offline sync we need to create another task & PR. @sergeymomot could create ticket for that.
> 
> I have fixed code that you requested to change. Thank you for review.

@forgotvas It makes sense to me. I've looked over the requested changes, and we are good to merge. 🎉

2024-05-09 12:56 UTC, shafqat-muneer approved these changes

2024-05-13 07:10 UTC, shafqat-muneer approved these changes

2024-05-16 13:36 UTC, merged