feat: course home navigation
openedx/openedx-app-ios pull request #446
Opened 2024-05-31 13:21 UTC by IvanStepanok

## Quick Preview

https://github.com/openedx/openedx-app-ios/assets/128456094/7e67e77c-f90c-462f-910b-053f7d9b6aad

## Pay attention ⚠️
❌ "COURSE_NESTED_LIST_ENABLED" removed
✅ "COURSE_DROPDOWN_NAVIGATION_ENABLED" added

Old implementations in CourseStructureNestedListView.swift and CourseStructureView.swift are removed.

2024-05-31 13:21 UTC, openedx-webhooks commented
Thanks for the pull request, @IvanStepanok! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2024-05-31 13:53 UTC, volodymyr-chekyrta commented
The arrow is pointing in the wrong direction
<img width="780" alt="image" src="https://github.com/openedx/openedx-app-ios/assets/127732735/4a7324fb-f03c-4ea5-9288-b1a5608885ae">

2024-05-31 14:09 UTC, volodymyr-chekyrta commented
By design, arrows should be displayed only in sections with assignments.
| Design | Device |
|----------|----------|
| <img width="410" alt="image" src="https://github.com/openedx/openedx-app-ios/assets/127732735/6d9a75c1-99f3-4b00-b0f8-27f03639efe0"> | <img width="415" alt="image" src="https://github.com/openedx/openedx-app-ios/assets/127732735/8308f0e7-10c0-4411-81b9-c7c18a498766"> |

2024-05-31 14:16 UTC, volodymyr-chekyrta requested changes
Good overall; please address the following feedback

2024-05-31 14:16 UTC, volodymyr-chekyrta commented on Course/Course/Presentation/Subviews/CustomDisclosureGroup.swift
> +                                        }, label: {
Please format Button to the "each param on own line" style.
```
Button(
action: {
...
, 
label: {
...
```

2024-05-31 15:34 UTC, IvanStepanok commented
@volodymyr-chekyrta Thanks for the review! All requested changes have been made🙌

2024-05-31 15:35 UTC, volodymyr-chekyrta approved these changes
Looks good to me.
PR is ready for product/design review.

2024-06-03 17:43 UTC, sdaitzman commented
Hi @IvanStepanok, this looks great overall! A couple of design questions/feedback I wanted to check on:

1. In light mode, sections should use the light theme `shade` color `#F9FAFB` as their background color. It looks like this might be missing from the video
2. In dark mode, the download icon should use the lighter `dark theme accent text` color `#879FF5` for contrast/accessibility reasons

Both of these are color-related, and the video compression makes it a bit ambiguous whether these colors are already being used, so I wanted to confirm

2024-06-04 20:38 UTC, IvanStepanok commented
Hi @sdaitzman and thanks for paying so much attention to details!
Please, take a look at my changes. The download icon had the wrong color, but in the light theme, not in the dark☺️

![Simulator Screenshot - iPhone 15 - 2024-06-04 at 23 20 50](https://github.com/openedx/openedx-app-ios/assets/128456094/ebfa65e9-c1d9-4662-ad89-506c2a7950cd)

2024-06-05 14:37 UTC, sdaitzman commented
Thanks so much @IvanStepanok! Just to confirm, is the download icon in dark mode using [`#879FF5`](https://www.figma.com/design/iZ56YMjbRMShCCDxqrqRrR/Open-edX-Mobile-App-All-Screens-v2.1?node-id=12096-95006&t=gqaiAEFAMSBQE7Vt-11)? In that screenshot, I see a value of #5378F8, but it's possible that's just an image encoding/color space variation.

Other than that, everything looks great to me/ready to merge from a design standpoint, thanks for these updates!

<img width="508" alt="Screenshot 2024-06-05 at 10 31 19 AM" src="https://github.com/openedx/openedx-app-ios/assets/1499476/0528006e-b746-4049-b7dd-0c0866e2b0b3">

2024-06-05 20:04 UTC, IvanStepanok commented
Hi, @sdaitzman 
For some reason when you load icons and make a screenshot, they have a little difference in color measurement. I think is because of different color profiles used on real device and the simulator. I found a topic about this, but anyway, I think all we can do is just accept the rules🙌

2024-06-06 12:56 UTC, rnr requested changes

2024-06-06 12:56 UTC, rnr commented on Course/Course/Presentation/Outline/CourseOutlineView.swift
> -                                if viewModel.config.uiComponents.courseNestedListEnabled {
@IvanStepanok 
we had logic when `courseNestedListEnabled==true` we skip VerticalsView and go to content directly. Could you please add the same? Thank you

2024-06-07 11:10 UTC, rnr requested changes

2024-06-07 11:10 UTC, rnr commented on OpenEdX/Router.swift
> -        if isCourseNestedListEnabled || currentCourseTabSelection == CourseTab.dates.rawValue {
this condition should be present. please use new added flag here. Thank you

2024-06-07 11:12 UTC, rnr requested changes

2024-06-07 11:12 UTC, rnr commented on OpenEdX/Managers/PipManager.swift
> -        if !isNestedListEnabled && holder.selectedCourseTab != CourseTab.dates.rawValue {
the same here - please use here new added flag. Thank you

2024-06-07 12:03 UTC, rnr approved these changes

2024-06-07 12:18 UTC, merged

2024-06-07 12:18 UTC, openedx-webhooks commented
@IvanStepanok 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-app-ios&entry.867055334=https://github.com/openedx/openedx-app-ios/pull/446&entry.1484655318=https://github.com/IvanStepanok&entry.752974735=2024-05-31+13:21&entry.1917517419=2024-06-07+12:18&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->